name: publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  ktfmt:
    uses: ./.github/workflows/ktfmt.yml

  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: [ ktfmt, test ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - uses: gradle/actions/setup-gradle@v6

      - name: Publish package
        run: ./gradlew publish
        env:
          VERSION: ${{ github.ref_name }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
